# Generated by Django 2.0.1 on 2018-01-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.TextField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Твит',
                'verbose_name_plural': 'Твиты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='twit',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='textbox.User'),
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='textbox.User'),
        ),
        migrations.AddField(
            model_name='reply',
            name='twit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='textbox.Twit'),
        ),
        migrations.AddField(
            model_name='like',
            name='twit_liked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='textbox.Twit'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_liked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='textbox.User'),
        ),
    ]
